### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by vangorra** [sf-wind/meteor-velocity-travis-ci#1]
Trying to run this for our project but it doesn't work. While I doubt this is a bug with this project, the resolution may help with documentation.

``` javascript
// package.js
Package.onTest(function(api) {
    api.use([
        'prime8:velocity-teamcity-reporter',
        'sanjo:jasmine'
    ], 'server');

    api.addFiles('tests.js', 'server');
});
```

**Comment by sf-wind** [comment]
What is the problem you are trying to address?

**Comment by vangorra** [comment]
Not sure. I figured the build script may have some issues. I just rewrote the script and all its well.
